name: ceres
dependencies:
- openssl=1.0.2h=1
- pip=8.1.2=py27_0
- python=2.7.12=1
- readline=6.2=2
- setuptools=25.1.6=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - click==6.6
  - flask==0.11.1
  - itsdangerous==0.24
  - jinja2==2.8
  - mako==1.0.4
  - markupsafe==0.23
  - peewee==2.8.2
  - py==1.4.31
  - pycrypto==2.6.1
  - pytest==2.9.2
  - requests==2.11.0
  - simplejson==3.8.2
  - werkzeug==0.11.10
